### ISSUE TITLE
[Bug] Snow doesn't "stick to ground" in Winter, in Multiplayer

### ISSUE THREAD

**Issue by abboip** [Glitchfiend/SereneSeasons#114]
Tested in Forge 2768 and 2796, with no other mods added.

When in a Winter subseason, biomes where it doesn't otherwise snow normally will have snow fall -- but it will not stick to the ground. This happens in multiplayer, but does not happen in singleplayer.

**Comment by Forstride** [comment]
Does the server have the mod installed (Since the mod *can* technically function client-side only with minor issues), and do you have the same config as the server?  I've seen a few other people reporting this, but I gotta make sure before determining that it's caused by something with the mod itself.

**Comment by abboip** [comment]
Yup, absolutely on both. This occurred in a modpack I was using for a private server with friends, and then I was able to also confirm it with just the mod installed. I made sure the configs matched with the modpack and with this test.

**Comment by Forstride** [comment]
Hmm, okay.  I think it might have something to do with our recently added dimension whitelist.  Gonna have to get our lead coder to look into it when he has time.

**Comment by Marfjeh** [comment]
What also happend to me its snowing in the spring, but the snow is disappearing. and it rains in the winter and then snow spawns on the ground...

**Comment by Forstride** [comment]
I tested it myself, and it seems to be some kind of weird temperature discrepancy between singleplayer and multiplayer,  It seems to snow properly in biomes like the Extreme Hills and Taiga, but the Forest and Plains aren't accumulating any like they should.

Doesn't make sense at all though, as singleplayer is essentially just a server being run locally from the client.  I told our lead coder about it, and while he hasn't looked into it yet, it definitely shouldn't be happening.

**Comment by Adubbz** [comment]
In case people are interested in what the issue was, basically https://github.com/Glitchfiend/SereneSeasons/commit/7ef6dfecbcb8a9ab40bf156b59525b9f3bd6311d switched to using our getFloatTemperature code, which relied on SeasonHandler.clientSeasonCycleTicks which is only set client-side. The above commit fixes that
