### ISSUE TITLE
Disable spring/summer/autumn crops in cold biomes

### ISSUE THREAD

**Issue by ignatferum** [Glitchfiend/SereneSeasons#121]
I tried to disable crops in the configuration file, but then all crops were disabled, including winter crops.

**Comment by Forstride** [comment]
I'm not sure what exactly you're asking.  Snowy biomes already have it so that only winter crops can grow.  Likewise, tropical biomes can only grow summer crops.

The disable crops feature is supposed to be a complete override for stuff like the Biomes O' Plenty Wasteland biome and other biomes where no crops should grow at all, regardless of season.

**Comment by ignatferum** [comment]
I apologize, I thought that the biome that is snowing is a cold biome. But it turned out this is a temperate biome in which it snows in the autumn)
