### ISSUE TITLE
The right config for the change of seasons

### ISSUE THREAD

**Issue by kellixon** [Glitchfiend/SereneSeasons#126]
MC 1.12.2. B3M 1.12.2-02, SereneSeasons 1.2.15. Without B3M, the seasons change, but with it, they don't.
What are the correct settings to expose for the duration of the day 5 times and change of seasons. Help(
My config - B3M (https://pastebin.com/wAeh06hc), SereneSeasons (https://pastebin.com/XBWAYY7K).

**Comment by kellixon** [comment]
B3M (https://minecraft.curseforge.com/projects/time-speed-mod?gameCategorySlug=mc-mods&projectID=221053). With this mods for long nights and days I do not change seasons (29 days have passed). Is constantly Early winter(

**Comment by Forstride** [comment]
It literally says in the description on their CurseForge page that _they_ have support for _us_, so clearly it must work in some form.  It sounds like they actively change our season time though, so you probably shouldn't change the day length in our config.

**Comment by SoggieWafflz** [comment]
That mod takes full control of serene seasons, because it uses it's own month/date system. 
https://www.curseforge.com/minecraft/mc-mods/time-speed-mod
When using this mod with serene seasons, new worlds start on january 1st, and thus during winter, and the seasons don't follow the 7-day-per-subseason, instead being based on the calendar. I'm trying to find a way to change both the starting date, and how long each month lasts.

If I can't, then people ought to turn off the serene seasons control in the B3M config, and use the same day time multiplier for B3M and serene seasons config
