### ISSUE TITLE
Serene Seasons Crash on Startup in 1.7.10

### ISSUE THREAD

**Issue by Tomcatchriss** [Glitchfiend/SereneSeasons#234]
## Issue Report

</br>

### What's the issue you encountered?

Using Forge 10.13.4.1614 for MC 1.7.10 and Serene Seasons for 1.7.10 - Version 1.2.18 crashing on startup.</br>

### How can the issue be reproduced?

I'm only using forge-1.7.10-10.13.4.1614-1.7.10-universal.jar and SereneSeasons-1.7.10-1.2.18.jar as the only one mod.</br>

I'm using a linux server running Ubuntu and Java OpenJDK 1.8.0_242.</br>

### Logs
[Crash Log](https://pastebin.com/jHKSCgWq)
</br>

### Mod Version
SereneSeasons-1.7.10-1.2.18.jar</br>

**Comment by Forstride** [comment]
The 1.7.10 port was not made by us

https://github.com/DarkShadow44/SereneSeasons/issues

**Comment by LaryWulf** [comment]
U are really dumb donest care about the best version of Minecraft 1.7.10 , alot people playing then news version of Minecraft, 1.20.2 sucks alot looks crap runs crap,  u waste more time news version of Minecraft then, keeping support 1.7.10 people loaves, u really need to think about again.

**Comment by BroderMibran** [comment]
I kind of agree....

I still prefer 1.7.10 because of it capability of being able to run plugins and mods together, just show me one functionally way to do this in minecraft 1.16+... and yes I heard of sponge and spigot, but no you cannot just put the plugins into the mod-folder and make them all run together by a mod running the plugins, it simply just not working.

First of all you get a non-mod message in the console that they are inside the mod-folder and then the mod running cannot either not recognize them and thereby ignores the plugins, crash or simple not capable of running them.

I accept that some people believe that 1.8 is best pvp version which is why I made some servers in 1.8.9, choosing between mods or plugins. I even upgrades to 1.10.2 but I seen what they added to the game afters this version and it is not really that appealing.. so I prefer 1.8.9 to 1.10. 2 for mods or plugins, and 1.7.10 for both of good reason.

The combination of mods and plugins just makes it so mush easier to either control, extend or direct your server in so many ways you feel needed.

So I kind of find it a bit arrogant that just because it is not new we have to be forced to a newer not very capable version of minecraft with crappy loading times, tons of errors, incapable plugins/mods and a lot of new functions which you rather have to finds ways (such as mods/plugins) to disable than add/use in your server.

I was part of bukkit, not an official developer, but I helped develop some of the plugins, and one of the rules at bukkit many have forgotten was, plugins should be free to use and you can voluntarily donate the developers, and any one charging you for a plugin is not part of bukkit and you should not use it... 

Today some of the most popular or new great plugins/mods are not free of charge you have to pay to get like new updated versions of mcmmo which was of no charge to begin with...

So tell me why this is so much better...

I can understand you if you depart versions of 1.7.10 of this mod and as much as I can see your made this mod for minecraft version 1.12.1 and above, which I accept and that is okay if you did not make the 1.7.10 capable version and therefore you should not be responsible of this version you did not even make, unless you feel for it which is totally fine if you don't.

But don't just say that everyone finds it confusing, because you can't be sure of this, and if you find it confusing that okay, but it just don't justify that everyone else would feels it the same way as you do.
