### ISSUE TITLE
[Suggestion] Config options to allow mobs to spawn more in specific seasons

### ISSUE THREAD

**Issue by Sunconure11** [Glitchfiend/SereneSeasons#243]
## Feature Request

Seasonal mob spawns

### What feature are you suggesting?

One should be able to make certain mobs spawn more often in certain seasons, and allow both temperate and tropical seasons. One could even shut off said mob spawns for said season. Any modded or vanilla mob could be set to spawn more, less, or not at all for a given season. For instance, modded mosquitoes could spawn a bunch in the summer, and be entirely absent in the winter.</br>

### Why should it be added?

This would increase customizability, immersiveness, and depth of this mod in a heavily configurable way.</br>

**Comment by Corvus20** [comment]
Breeding seasons could also be applied for animals, but that may be out of scope of this mod. Just an idea.

**Comment by Forstride** [comment]
I'm surprised I never closed/responded to this.  We had this in the past (Although it was just preventing spawns in winter), but the way mob spawns work can't really be changed dynamically without causing issues, at least based on what it was like back when we had that feature, otherwise we *would* still have it.
