### ISSUE TITLE
Optionally enable thunder-snowstorms during winter in a true/false config (for Charm compat if nothing else).

### ISSUE THREAD

**Issue by StygianEmperor** [Glitchfiend/SereneSeasons#300]
### What feature are you suggesting?

Optionally enable thunder-snowstorms during winter in a true/false config.

### Why should it be added?

1. I don't know why winter can't have thunder-snowstorms in the first place. Realism? I live in Texas so I have no idea. But I think this is an area where the Rule of Cool should apply if someone wants them to happen.
2. The mod [Charm](https://www.curseforge.com/minecraft/mc-mods/charm) ([Reforged](https://www.curseforge.com/minecraft/mc-mods/charm-reforged)) uses thunder-snowstorms as "blizzards," so essentially this makes it so it can't blizzard in winter.
3. Seems relatively easy to implement.

**Comment by Forstride** [comment]
I suppose it can have a very low chance, but we're not going to make it common just because some other mod adds blizzards that work using the normal thunderstorms.

**Comment by StygianEmperor** [comment]
Can’t it just be a config option to choose between what it is now and the default?

**Comment by Forstride** [comment]
Not sure why you're being passive aggressive after I literally said I'd consider adding it, but okay.

Point 1) Texas isn't exactly in a temperate region, so I can't help it if your view on seasons is skewed.  But in temperate regions, we don't get thunderstorms when it's 30 degrees Fahrenheit outside...

Point 3) Yes, it is easy to implement.  That isn't an issue at all, and I never said it was.

As for making it configurable, yes, that would also be possible, but the way it works uses two values for setting how long until it rains/storms (A base length and a random value that is added to it), and a value that checks how long it's been since it last rained/stormed (Or something along those lines...I didn't code the weather system).

So that'd be 6 values for each season, 24 total, most of which no one would change, and would bloat the config file and lead to confusion for other users.  There's more that we have to think about than JUST adding it exactly how a single person suggested it.

**Comment by StygianEmperor** [comment]
getting my meds regularly has been a nightmare during covid, sorry.

**Comment by Forstride** [comment]
Rain/thunderstorm frequency can now be changed per-subseason in the config as of 1.20.4
