### ISSUE TITLE
BOP Request

### ISSUE THREAD

**Issue by ProfessionaFiddler** [Glitchfiend/SereneSeasons#332]
Change what? Can you guys please not close my request in a splitsecond? I am not really following your thoughts, why don't you give me time to ask some questions?

I don't understand why is this such a hard and fast "no"? Your 2 best mods are just conflicting, because BOP already has specific seasonal biomes. Wouldn't it be rational to change that?

If something like that is, impossible, or just is really a bad implement, please explain a bit why

**Comment by Forstride** [comment]
You know you can still reply to an issue after it's been closed right...?  You are not helping your case *at all* by spamming new issues, and if you do it again, you will be blocked from our repositories.

On the topic at hand, no, it's not "impossible" to change.  It's just not worth completely overhauling how our leaves work and losing quality with the textures (Because you can't exactly have multiple shades when it's overlaying a single color...) and then adding special coloring in Serene Seasons when it's literally one person being persistent about it and not accepting no for an answer.  It's not a conflict, it's biomes specifically designed around being seasonal despite Minecraft not actually having seasons, just like vanilla's biomes are.

If we were to account for every biome designed around a specific season or whatever, we might as well just make a completely different biome mod that replaces every single biome in that case.  Either disable the biomes you somehow can't fathom existing while using Serene Seasons, or don't use either mod.

**Comment by ProfessionaFiddler** [comment]
I can? Oh, well this is new to me sorry...

**Comment by ProfessionaFiddler** [comment]
Well, first of all, I always thought a closed issue is, closed, from any further editing. So I was forced to create so many issues, even if I was wrong, nobody is spaming you because I chose to do so.

Secondly, different people have different goals. Some enjoy mods as they are, and others are activly in pursuit to enhance them, get the best mod pack, fix conflicting stuff. So when I am being persistant, it is a matter of determination, and has nothing to do with "can't deal with denyal". And I even wanted to see your explaination better.

Yet all you show in response, is ban threats, temperless shrug off because i am a one person who requests this. Again I did not know you could reply in closed section, sorry for spam. But you definitly could spare me the attitude. All my appeals have 0 insults, so I see no reason to respond with "either blacklist this or dont use that".

At least thanks for a vague explanation of why this is hard to implement. I'll try to do it myself then.
