### ISSUE TITLE
option to use vanilla time

### ISSUE THREAD

**Issue by Efimero** [Glitchfiend/SereneSeasons#34]
for mod compat, it would be good if there was an option to use vanilla time instead of the mod's own time for season calculations, that way seasons shouls stay synced even after using /time set and other commands that change time

I'm also concerned that sleeping may desync seasons under some circumstances

my specific concern is with the seasonal crops mod: https://minecraft.curseforge.com/projects/seasonal-crops?gameCategorySlug=mc-mods&projectID=291845
but probably applies to others

**Comment by Forstride** [comment]
1) We have an API that other mod developers can use.  Even if it did go by vanilla time, other mods wouldn't be able to tell how long a season lasts just by that alone.

2) Using */time set* reverts the global world time to 0, so that wouldn't keep it synced.  You're really not supposed to be using it in survival anyway, and in creative, you can just use a command to change the season to what you want it to be.

3) Sleeping doesn't desync seasons.  I have my own private server with the mod, and season progression has worked just fine between sleeping and everything.
