### ISSUE TITLE
Bonemeal in winter

### ISSUE THREAD

**Issue by MegaGamer265** [Glitchfiend/SereneSeasons#344]
In winter when u bonemeal plants or click on blocks they will get destroyd even bedrock.

**Comment by Forstride** [comment]
Please stop opening issues and not listing the version you're on.  We cannot do anything if we don't have that info, but I know for a fact you're on an older version, because I explicitly tested this and made sure it wasn't an issue on 1.16.5.  And we do not support any versions below that, as it says when opening a new issue...
