### ISSUE TITLE
Game crashes due to negative time

### ISSUE THREAD

**Issue by Nubidubi23** [Glitchfiend/SereneSeasons#345]
Crash log : https://pastebin.com/1qvLxf8Z

Tried editing the SeasonCycleTicks value with NBTexplorer but that wasn't it , removing the config didn't work either

**Comment by qMatriiix** [comment]
Same thing happened to me on my dedicated server. I'm not able to relaunch the server at all. Getting the same crash log. Playing the modpack "Better Minecraft [PLUS]".

**Comment by Forstride** [comment]
So far the only people that have reported this issue have all been using the Better Minecraft modpack, and nothing in the mod has changed within the past 7 months or so that would cause this.  You may need to report the issue to them as well, as right now they're the common denominator with this.

Likewise, if you are doing something like /time add 9999d, as someone else who had the same issue did, do not do this.  You are going past the max integer value, and while yes, we can probably add a check for this, doing something like this is deliberately screwing up your own world.

**Comment by qMatriiix** [comment]
Copy that! Thank you!

**Comment by joshiejack** [comment]
> So far the only people that have reported this issue have all been using the Better Minecraft modpack

Send everyone screaming at me. I fucked up when I changed some code in one version/added some sleep configs with my morpheus compat and that pack updates mods fairly frequently >>> https://github.com/Harvest-Festival/Simply-Seasons/commit/c35caee0dac36d7d9545eb223e9a8a6c238db0d9#diff-98dc2a66f822211db20556660b55ee9014d2b98f544da2b0b427b39a5cb8f36dL27

(Folks using the pack either remove my mod or morpheus to prevent it in the future until the pack either updates my mod or removes it :P, although would have to fix the world time with nbt editor i assume too to sort it now)

**Comment by Forstride** [comment]
> Send everyone screaming at me. I fucked up when I changed some code in one version/added some sleep configs with my morpheus compat and that pack updates mods fairly frequently >>> [Harvest-Festival/Simply-Seasons@c35caee#diff-98dc2a66f822211db20556660b55ee9014d2b98f544da2b0b427b39a5cb8f36dL27](https://github.com/Harvest-Festival/Simply-Seasons/commit/c35caee0dac36d7d9545eb223e9a8a6c238db0d9#diff-98dc2a66f822211db20556660b55ee9014d2b98f544da2b0b427b39a5cb8f36dL27)

I'm not quite sure I understand what you linked, or how that relates to Serene Seasons/the Better Minecraft modpack lol

**Comment by Forstride** [comment]
Wait what the hell...?  They included BOTH Serene Seasons and Simply Seasons in the modpack...

Yeah, I think this can be closed at this point.

**Comment by joshiejack** [comment]
> 
> I'm not quite sure I understand what you linked, or how that relates to Serene Seasons/the Better Minecraft modpack lol

I was accidentally setting the time to (the current time + the current time + the next day) with morpheus so it would overflow and cause the negative time. (Had to add support because morpheus doesn't wake players up after sleeping automatically and my mod changes the day length based on the season). (Mod is in that pack that's why it's relevant :P). (There's no issue with using both since I use your seasons if it's there).

**Comment by regfsdfgsadgf** [comment]
Is there any way to fix this issue?

**Comment by JasZhe** [comment]
> Is there any way to fix this issue?

@regfsdfgsadgf I managed to figure it out. 

I went to my `<world file (in my case .minecraft/my_world)>/data/seasons.dat` opened that in 
https://irath96.github.io/webNBT/

Notice the negative time value here 
![Image](https://github.com/user-attachments/assets/9a971c8f-f03f-4f85-b98e-77c304c504ee)

and update it to be a non-negative value i.e. i just changed it to 1000
