### ISSUE TITLE
Non-wheat crops lacking seasonal information

### ISSUE THREAD

**Issue by MarioSMB** [Glitchfiend/SereneSeasons#383]
### What's the issue you encountered?

Both Wheat Seeds and the Wheat item display their fertile seasons, while only Beetroot Seeds (and not the Beetroot item) shows its seasonal information.  
This consistency issue affects the following vanilla crops:  
- Pumpkin
- Beetroot
- Melon / Melon Slice

### How can the issue be reproduced?

N/A

### Mod Version

7.0.0.13

**Comment by MarioSMB** [comment]
I do not know which solution would be preferable (removing Wheat from the tag or adding the other crops to it), but I do recommend taking some action as this inconsistency is propagating to other mods adding support for the mod.

**Comment by Forstride** [comment]
If anything the wheat item should just not have the tag.  I think it only has it because it's technically the item block for the actual wheat crop, but it doesn't really need the tooltip info to work properly.

**Comment by Forstride** [comment]
Looked into this now that I've been working on the mod and bit, and as far as I can tell, it's because the wheat "item" is just for the crop block itself, so it gets automatically registered.  Whereas with the other crops, the harvested items are completely separate, and in the case of pumpkins/melons, those aren't actually what grows (The stems are).
