### ISSUE TITLE
SereneSeasons is NOT compatible with OTG and Biome Bundle

### ISSUE THREAD

**Issue by ExDomino** [Glitchfiend/SereneSeasons#40]
You shold change the note in your CurseForge page that indicates your mod is compatible with all biome mods. It's false, it's not compatible with Biome Bundle! Cold biomes are not supported and ice become water in those biomes in spring and a lot of water and lag are generated in cause of that. You should also add a warning that your mod can generate a lot of grief in a world and there is nothing in config to disable ice/water behavior. We have been forced to remove your mod and restore a backup to repair damages on our server. Of course, it's not your fault, but a simple warning in your home page would be appreciated, and the removing of the note that it's compatible with all biome mods as well. Biome Bundle is NOT compatible!

**Comment by Forstride** [comment]
So, I actually went out of my way to load up Biome Bundle and Serene Seasons, and I noticed nothing wrong with snowy biomes at all.  The Ice Plains biome was fine, and even a Taiga biome that had a little mound of snow and ice was just fine, and none of it melted.

If they're placing ice in biomes that AREN'T actually cold enough to get snow normally, that's THEIR problem.  We have to be able to melt ice in non-snowy biomes after it forms in Winter, otherwise any lakes or rivers that freeze over will remain frozen forever, and that'd look like shit.

So no, the mod isn't incompatible with Biome Bundle.  Their poor design choices are incompatible with us.  Do not make another issue about this subject, because I will just immediately close it.

**Comment by ExDomino** [comment]
It's maybe their fault, I agree, but it's still incompatible!
The fact of your mod is incompatible with another doesn't mean that your mod is bad.
You can says that this is Biome Bundle that is incompatible with your mod instead.

**Comment by Adubbz** [comment]
Sure, but this isn't an issue with Serene Seasons, and hence not something we can fix. If they're don't use biomes correctly that's their decision, but we're not going to pick up the pieces for them because of their poor design decisions.

**Comment by Adubbz** [comment]
Simply put, just because you put some snow in the middle of a desert doesn't make it as cold as the North Pole.

**Comment by Maxiride** [comment]
I know this is kinda of necro, but _Credit Where Credit's Due_, @ExDomino you simply made the mistake to assume that a biome name is related to it's actual temperature configuration, as I've mentioned [here](https://github.com/Glitchfiend/SereneSeasons/issues/38#issuecomment-396290272). Every mod did his job as fine as expected. If you are still interested in this just lower the biome temperatures in the configs 😉

**Comment by ExDomino** [comment]
https://image.noelshack.com/fichiers/2018/28/5/1531508870-autruche.jpg

**Comment by Doctormandow** [comment]
shit got heated
