### ISSUE TITLE
[1.20.1]Some Crops did not break when config is set to 2(break when grow)

### ISSUE THREAD

**Issue by LiAuTraver** [Glitchfiend/SereneSeasons#429]
### What's the issue you encountered?

For example, Melon is only matured in summer,so it should break in winter when crops config is set to 2 (break when grow)
however it did not break and even harvest melon block! Wheat do not break,either.
Only Tomatoes and Carrots break.
Outside vanilla, Farmer's delight's crops do not break,either.

### How can the issue be reproduced?

as shown above.

### Mod Version

1.20.1-9.0.0.43

**Comment by Shaen-12** [comment]
Since man turned from hunting-gathering to agrarian living, bread in some form or the other has been a staple. This is true for people across the world. From soft white breads to homemade flatbreads, there is perhaps no dish as ubiquitous as bread.

Across the Indian subcontinent, the chapatti or roti, as unleavened (made without yeast) flatbreads are known here, are a ubiquitous accompaniment to every meal. Breakfast, lunch, and dinner just wouldn’t be the same without the humble chapatti. And while it has gained much acceptance as a low-calorie food, given its lower [Glycemic Index](https://www.freedomfromdiabetes.org/blog/post/what-is-glycemic-index-gi-complete-knowledge/2666), not all varieties are equal, nor good for diabetics.
Wheat Nutrition
100 grams of wheat contain the following nutrition
Carbohydrates: 72 grams
Sugar 0.4 grams
Protein: 13.2 grams
Water: 10 – 11%
Calories: ~ 340
Fiber: 12- 15% (bran)
https://www.freedomfromdiabetes.org/blog/post/best-wheat-for-diabetes/2904

**Comment by Forstride** [comment]
In regards to the melon, there's nothing that can be done about it, since the fruit itself isn't considered a crop and doesn't call any of the Forge hooks we use for crop growth.  Only the stem does.

Likewise, if other crops don't use the relevant Forge crop/bonemeal hooks, whether they're modded *or* vanilla (Since some vanilla plants aren't patched by Forge to use them), they won't break at all.

That being said, wheat *should* be breaking, assuming it's winter and you're not in an area that's still fertile for crop growth (Tropical biome, deep underground, etc.), so ensure it's not an issue with a custom datapack if you're using one.

**Comment by LiAuTraver** [comment]
Thanks. Hope there will be a way that 'break when grow' could function effectively, only in that way could Minecraft be real Minecraft.
