### ISSUE TITLE
Add or Allow Tempest Compatibility

### ISSUE THREAD

**Issue by lostopkk** [Glitchfiend/SereneSeasons#448]
### Overview

Tempest is a regional rain mod that adheres more closely to Minecraft, making it more realistic. Adding compatibility would help the two move together for a more satisfying Minecraft experience.

https://modrinth.com/mod/tempest

to an issue that several seasonal mods have no way of enabling this mod to be compatible, I'm here to ask if there could be a possibility of this happening.

issue: https://github.com/lukebemishprojects/Tempest/issues/20#issuecomment-1907039244

### Why would this feature be useful?

makes Minecraft more satisfying, as working together would make things more synchronized and consistent with its applications in both Tempest and Serene Seasons

**Comment by Forstride** [comment]
The support would have to be on their end, but they clearly have no interest in adding it due to our license, which is pretty silly considering we have a publicly available API for a reason...

I mean I could give explicit permission, but they seem to already have their mind made up, so I'm not sure it'd make much of a difference.

**Comment by lukebemish** [comment]
Hey, just adding this (author of Tempest here).

Explicit permission would actually be something I can work with. Basically, I want to know that there's some version of your API that I can compile against and that that's definitely allowed under your licensing, and to have some sort of guarantee that you won't revoke that right in the future (for already published versions at least), which I can't guarantee with any of the current information I can find on your API and permissions to use it.

**Comment by Forstride** [comment]
@Adubbz would have to respond with the technical details for that since he's the one that handles that stuff, but anyway...I've been considering writing our own license that makes our intentions clear with how people can use our mods.  The main reason we went ARR is because the average person can't be bothered to read the details of other commonly used licenses with extensive details.

I mean we've had people fork our mods in the past and try to change the license because they didn't agree with the existing one, or try to bend the meaning of certain terms.  It was very frustrating and just became exhausting after a while, and ARR felt like a better way to make it so we could approve/deny things on a case-by-case basis, but I guess it also had the opposite effect and turned people away without them even wanting to inquire about it.

Overall, I'm not a FOSS enthusiast or whatever like most modders are, but I'm fine with people doing things like mod compatibility in this case.  I'm not gonna turn around and go after someone if they're acting in good faith and not just repurposing our code/assets for their own mods that aren't connected to us in any way, or trying to undermine us in some way.  I mean I don't even bother doing anything against people who *do* blatantly steal our assets either since it's too much of a pain to deal with, but I digress.

I don't know if I'll ever even end up writing our own license, since I really don't care that much about the legal side of things and just want people to respect our wishes for how our mods can be used.  I'd honestly rather just give explicit permission for things than have certain terms be misinterpreted, whether it's accidental, or intentionally done in bad faith.

So, if you're fine with that, this is me explicitly giving you permission to use Serene Seasons' API for the purpose of mod compatibility with Tempest, on any existing and/or future versions of the mod that are licensed as All Rights Reserved.

**Comment by lukebemish** [comment]
Thanks a bunch, that all makes sense to me!

**Comment by Adubbz** [comment]
Currently the intended way of using the mod’s api is by including the mod from Maven with Gradle. I’m just going to shamelessly copy and paste this from our Discord:

7. **How do I add your mods as a dependency in build.gradle?** 
First, make sure you have added the Forge Maven to be added to your ``buildscript -> repositories`` block:
```Gradle
buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
    }
    dependencies {
        <...>
    }
}

```

Then just add the mods to your dependency block, using the correct identifier as follows: ***com.github.glitchfiend:``ModName``-``modloader``:``x.x.x``-``y.y.y.y``***

``ModName`` is to be replaced with the name of the mod you're using (i.e. ``BiomesOPlenty``, ``TerraBlender``, etc.), ``modloader`` is to be replaced with the modloader you're using (``forge``, ``neoforge``, or ``fabric``), ``x.x.x`` is to be replaced with the Minecraft version, and ``y.y.y.y`` is to be replaced with the mod version.

```Gradle
dependencies {
    implementation fg.deobf("<dependency identifier here>")
}
```

**Comment by Adubbz** [comment]
If you’re looking for an example of how a mod can use Serene Seasons as an optional dependency you can see the [Tough As Nails repo](https://github.com/Glitchfiend/ToughAsNails)
