### ISSUE TITLE
A Server-Only Featureset

### ISSUE THREAD

**Issue by adriansnetlis** [Glitchfiend/SereneSeasons#467]
### Overview

Currently the mod requires client side installation to work at all. However, sometimes it would be great to just have it work server side with optional client-side installation (e.g. with some more visual parts only showing up if client-side is present). I am guessing this would require a separate version that omits some features which require client-side mod, so not sure how much work that would be. But I am certain a lot of people would be happy to have this.

### Why would this feature be useful?

This enables a lot of people running servers to use this mod (albeit not at it's full capacity) and still have the server accessible to users with vanilla installations.

**Comment by Forstride** [comment]
>But I am certain a lot of people would be happy to have this

I doubt it, because the biggest appeal of the mod is obviously the changing colors, which wouldn't work server-side.  Plus visuals/sounds for snow/rain need client-side changes to work properly with the seasons, and at that point you'd just be left with crop fertility, which would be pointless if you couldn't even see the seasons changing properly.

So ultimately, we have no interest in doing this.  It'd be a lackluster experience, and really wouldn't benefit as many people as you think.
