### ISSUE TITLE
Add seasonal crops

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/SereneSeasons#5]
Crops planted outdoors will only be able to grow in whatever season they're for.  They'll have to be planted indoors out of season, in a building made of greenhouse glass.

Vanilla crop listings:

Wheat - Summer/Autumn
Carrots - Spring
Potatoes - Spring
Beetroot - Autumn
Melons - Summer
Pumpkins - Autumn

**Comment by Ash70** [comment]
Please give us a config this time to add crops from other mods.

**Comment by Forstride** [comment]
There will be a config file.

**Comment by WrongWeekend** [comment]
I mentioned some of this in Discord already but I feel I can explain my idea more completely here:

The ability to tie crop death to a minimum/maximum biome temperature (which ought to rise higher than the default in summer and drop lower than the default in winter) as opposed to the current season "state" would allow more dynamic growing seasons for different crops as well as crop death from overheating. It would also work better with custom biomes from OTG, RTG, and other mods with minimal to no further configuring by using a commonly shared vanilla characteristic.

For example, sugarcane may only be able to grow at a minimum temperature of 0.9 and a maximum of 2.2 (values are totally subjective). So a warmer biome, or at least one with a temperature that stays within the limits for more or all of the seasons, would have a longer or year-round growing season for sugarcane, unless it happens to get too hot. A biome with a temperature range that is always outside the limits (like Cold Taiga, or a custom biome with a ridiculously high temperature like 5.0) would never be able to support unsheltered sugarcane, no matter the season.

A crop like beetroot may possible only grow between 0.2 and 1.0 (again, the specific values are totally subjective). So a cooler biome would have a longer growing season for beetroot, provided it does not get too cold. But a warmer biome during the summer will get too hot for the beetroot, killing them off.

Wheat may only grow between 0.5 and 1.5, cactus between 1.5 and 2.5, potatoes between 0.2 and 1.2, and so on. Players can decide what min or max temperature turns their crops into dead crops. Ultimately most farming will still follow the common pattern of growth in the spring/summer and harvest/death in autumn/winter due to the temperatures the crops naturally grow in. However, opting for temperature as the variable rather than current season will maintain the overall effects of seasons while opening up possibilities like extremophile plants and varying growing seasons based on biome and crop type.

**Comment by Ash70** [comment]
@WrongWeekend I agree a system like that would be much more flexible and fun. However may I make a further suggestion if it is decided to go this road:

Give each crop an extra option: `perennial = true | false` which determines if the crop either dies or reverts back to stage 0.
