### ISSUE TITLE
SereneSeasons partially working?

### ISSUE THREAD

**Issue by Artres** [Glitchfiend/SereneSeasons#71]
Hello there!
  I bet you can guess why I'm here (the title and the fact that I'm in the issues section might have been what had given it away), but yes. I'm having problems that I'm thinking maybe is a compatibility issue if not a bug.

Screenshot: https://imgur.com/a/7tQ8ZXw
(A picture is worth a thousand words, no?)

Anyway, the trees don't seem to be changing with seasons, that is besides the Greatwood trees at the sides. I understand that evergreen trees exist but not even the birch trees (such as the one at the near center of the shot have changed). 

Maybe I'm just messing something up? The biome is a 'Birch Forest' but I've checked other biomes such as a Jungle one and not even the trees there have turned red/amber. The in-game season is winter just to note.

Modlist: https://pastebin.com/3mW7WUZN

Thank you for reading this to the end. Sorry if I've wasted your time with something simple or stupid, I can be an idiot sometimes. If you can help, that's great, if not, thanks anyway. ^^

**Comment by Forstride** [comment]
Birch leaf color changing was only recently introduced.  Make sure you're using the latest version of the mod.

If you're using a texture pack, that might also affect it.  We have to override the birch leaf coloring, but if you're using a texture pack that has its own birch leaf color, or doesn't use one, then it'll likely override our coloring.

Also, tropical biomes don't change colors as drastically as temperate biomes, because they do not use temperate seasons.  They have their own tropical seasons.

**Comment by Forstride** [comment]
You'll have to try to edit the texture pack, or just deal with not having birch colors change
