### ISSUE TITLE
[Suggestion] Pam's Hanging Fruits

### ISSUE THREAD

**Issue by LordDan1989** [Glitchfiend/SereneSeasons#82]
The latest version of SS states in the change-log that 

> Allowed growable blocks to be listed in the crop fertility config, for crops that don't have seed items.  This includes saplings, flowers from other mods, and so on.

Does this include the 'non-ripe' fruit that grows under Pam's Fruit Trees? I've added the apple block (harvestcraft:pamapple) to the Summer fertility list and set the season to Winter and they still grow.
Is it possible to prevent Pam's hanging fruits from growing during seasons?

I'm referring to these: 
![Pam's Fruit Trees](https://usoog.com/sites/default/files/2014-06-29_20.29.52.png)

**Comment by Forstride** [comment]
There's probably nothing we can do to allow these to work if they don't use the proper Forge hooks to cancel growth events.

**Comment by TheInventrix** [comment]
I went digging around a bit and long story short, it isn't an issue of growth events.

The reason that fruit doesn't work with the seasons is because initSeasonCrops *only* references IPlantable items and the fruit blocks are not plantable items. Would it break things to change it to IGrowable to include things that can only spawn on their own, like the fruit blocks?

**Comment by TheInventrix** [comment]
Ah.... thanks. I am very new to mod code, I didn't see that part. (I was basing it partly off of the whole fertility tooltip thing, but I think that was a red herring.) Sorry for wasting your time! I'll probably go do something awful to my copy of HarvestCraft to try to make this work, then.
